publishDir = "docs"
baseURL = 'https://reverb256.github.io/hairathome/'
languageCode = 'en-ca'
title = 'Hair@Home'
theme = 'hairathome'

[params]
  description = "Mobile hair stylist in Winnipeg. Quality haircuts at your convenience."
  phone = "(204) 557-2287"
  email = "info@hairathome.ca"
  location = "Winnipeg, MB"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.8

[minify]
  minifyOutput = true
